// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a T4 template.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Microsoft.ML.Data;

namespace InputModelNameSpace
{
    public class InputModel
    {
        [ColumnName("Index"),LoadColumn(0)]
        public int Index { get; set; }

        [ColumnName("User Id"),LoadColumn(1)]
        public string UserId { get; set; }

        [ColumnName("First Name"),LoadColumn(2)]
        public string FirstName { get; set; }

        [ColumnName("Last Name"),LoadColumn(3)]
        public string LastName { get; set; }

        [ColumnName("Sex"),LoadColumn(4)]
        public string Sex { get; set; }

        [ColumnName("Email"),LoadColumn(5)]
        public string Email { get; set; }

        [ColumnName("Phone"),LoadColumn(6)]
        public string Phone { get; set; }

        [ColumnName("Date of birth"),LoadColumn(7)]
        public DateTime Dateofbirth { get; set; }

        [ColumnName("Job Title"),LoadColumn(8)]
        public string JobTitle { get; set; }

    }
}

